### ISSUE TITLE
"tag too large to fit into the unused bits" on aarch64

### ISSUE THREAD

**Issue by ignatenkobrain** [stjepang/coco#18]
```
failures:
---- src/epoch/atomic.rs - epoch::atomic::Owned<T>::with_tag (line 598) stdout ----
	thread 'rustc' panicked at 'test executable failed:
thread 'main' panicked at 'tag too large to fit into the unused bits: 5 > 3', src/epoch/atomic.rs:66:4
note: Run with `RUST_BACKTRACE=1` for a backtrace.
', src/librustdoc/test.rs:315:16
note: Run with `RUST_BACKTRACE=1` for a backtrace.
---- src/epoch/atomic.rs - epoch::atomic::Ptr<'scope, T>::tag (line 833) stdout ----
	thread 'rustc' panicked at 'test executable failed:
thread 'main' panicked at 'tag too large to fit into the unused bits: 5 > 3', src/epoch/atomic.rs:66:4
note: Run with `RUST_BACKTRACE=1` for a backtrace.
', src/librustdoc/test.rs:315:16
---- src/epoch/atomic.rs - epoch::atomic::Ptr<'scope, T>::with_tag (line 851) stdout ----
	thread 'rustc' panicked at 'test executable failed:
thread 'main' panicked at 'tag too large to fit into the unused bits: 5 > 3', src/epoch/atomic.rs:66:4
note: Run with `RUST_BACKTRACE=1` for a backtrace.
', src/librustdoc/test.rs:315:16
failures:
    src/epoch/atomic.rs - epoch::atomic::Owned<T>::with_tag (line 598)
    src/epoch/atomic.rs - epoch::atomic::Ptr<'scope, T>::tag (line 833)
    src/epoch/atomic.rs - epoch::atomic::Ptr<'scope, T>::with_tag (line 851)
```

Happens only on aarch64, armv7hl/i686 fail due to #17 and s390x/ppc64/ppc64le/x86_64 just work.

**Comment by stjepang** [comment]
It looks like the problem is that `mem::align_of::<u64>()` equals 4 instead of 8 on aarch64. I'll fix this.

May I ask where you got all these different architectures to test the library on? I'd be interested in running the tests myself. :)

**Comment by ignatenkobrain** [comment]
@stjepang that's Fedora Project builders... I'm afraid that you can't easily get access because that would require to becoming package maintainer in Fedora.. But you can anytime ask me to run tests there, I would be happy to do so.

**Comment by ignatenkobrain** [comment]
Just FYI, this problem appeared on i686 as well... https://kojipkgs.fedoraproject.org//work/tasks/4654/23044654/build.log

```
---- src/epoch/atomic.rs - epoch::atomic::Owned<T>::with_tag (line 598) stdout ----
	thread 'rustc' panicked at 'test executable failed:
thread 'main' panicked at 'tag too large to fit into the unused bits: 5 > 3', src/epoch/atomic.rs:66:4
note: Run with `RUST_BACKTRACE=1` for a backtrace.
', src/librustdoc/test.rs:315:16
note: Run with `RUST_BACKTRACE=1` for a backtrace.
---- src/epoch/atomic.rs - epoch::atomic::Ptr<'scope, T>::tag (line 833) stdout ----
	thread 'rustc' panicked at 'test executable failed:
thread 'main' panicked at 'tag too large to fit into the unused bits: 5 > 3', src/epoch/atomic.rs:66:4
note: Run with `RUST_BACKTRACE=1` for a backtrace.
', src/librustdoc/test.rs:315:16
---- src/epoch/atomic.rs - epoch::atomic::Ptr<'scope, T>::with_tag (line 851) stdout ----
	thread 'rustc' panicked at 'test executable failed:
thread 'main' panicked at 'tag too large to fit into the unused bits: 5 > 3', src/epoch/atomic.rs:66:4
note: Run with `RUST_BACKTRACE=1` for a backtrace.
', src/librustdoc/test.rs:315:16
failures:
    src/epoch/atomic.rs - epoch::atomic::Owned<T>::with_tag (line 598)
    src/epoch/atomic.rs - epoch::atomic::Ptr<'scope, T>::tag (line 833)
    src/epoch/atomic.rs - epoch::atomic::Ptr<'scope, T>::with_tag (line 851)
```

**Comment by stjepang** [comment]
I've just published a new version that should fix the problem.
